### ISSUE TITLE
'Cache data source' does not work when omitting all constraints

### ISSUE THREAD

**Issue by AliceBalfanz** [CCI-Tools/cate-webui#68]
When requesting a data source and selecting `cache data source`, an error occurs (see below screenshot). The error does not occur, when omitting  `cache data source`. It also does not appear when setting `time constraint` and `variable constraint` together with selecting  `cache data source`. 

![image](https://user-images.githubusercontent.com/23457217/89633092-96d48380-d8a3-11ea-95a5-702c2923b0a7.png)

```
Job: Opening data source "esacci.OZONE.mon.L3.NP.multi-sensor.multi-platform.MERGED.fv0002.r1"
Message: Failed to synchronize data source "esacci.OZONE.mon.L3.NP.multi-sensor.multi-platform.MERGED.fv0002.r1": HTTP Error 308: Permanent Redirect
Code: -32003
Method: set_workspace_resource
Exception: cate.core.ds.DataAccessError

Traceback (most recent call last):
  File "/home/alicja/Desktop/projects/cate/cate/ds/esa_cci_odp.py", line 1270, in _update_ds_using_http
    urllib.request.urlretrieve(actual_url, filename=dataset_file, reporthook=reporthook)
  File "/home/alicja/miniconda3/envs/cate-env/lib/python3.7/urllib/request.py", line 247, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/home/alicja/miniconda3/envs/cate-env/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/home/alicja/miniconda3/envs/cate-env/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/home/alicja/miniconda3/envs/cate-env/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/home/alicja/miniconda3/envs/cate-env/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/home/alicja/miniconda3/envs/cate-env/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/home/alicja/miniconda3/envs/cate-env/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 308: Permanent Redirect

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/alicja/Desktop/projects/cate/cate/util/web/jsonrpchandler.py", line 209, in send_service_method_result
    result = future.result()
  File "/home/alicja/miniconda3/envs/cate-env/lib/python3.7/concurrent/futures/_base.py", line 428, in result
    return self.__get_result()
  File "/home/alicja/miniconda3/envs/cate-env/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/home/alicja/miniconda3/envs/cate-env/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/alicja/Desktop/projects/cate/cate/util/web/jsonrpchandler.py", line 306, in call_service_method
    result = method(*method_params, monitor=monitor)
  File "/home/alicja/Desktop/projects/cate/cate/webapi/websocket.py", line 299, in set_workspace_resource
    monitor=monitor)
  File "/home/alicja/Desktop/projects/cate/cate/core/wsmanag.py", line 371, in set_workspace_resource
    workspace.execute_workflow(res_name=res_name, monitor=monitor)
  File "/home/alicja/Desktop/projects/cate/cate/core/workspace.py", line 667, in execute_workflow
    self.workflow.invoke_steps(steps, context=self._new_context(), monitor=monitor)
  File "/home/alicja/Desktop/projects/cate/cate/core/workflow.py", line 627, in invoke_steps
    steps[0].invoke(context=context, monitor=monitor)
  File "/home/alicja/Desktop/projects/cate/cate/core/workflow.py", line 318, in invoke
    self._invoke_impl(_new_context(context, step=self), monitor=monitor)
  File "/home/alicja/Desktop/projects/cate/cate/core/workflow.py", line 980, in _invoke_impl
    return_value = self._op(monitor=monitor, **input_values)
  File "/home/alicja/Desktop/projects/cate/cate/core/op.py", line 216, in __call__
    return_value = self._wrapped_op(**input_values)
  File "/home/alicja/Desktop/projects/cate/cate/ops/io.py", line 84, in open_dataset
    monitor=monitor)
  File "/home/alicja/Desktop/projects/cate/cate/core/ds.py", line 675, in open_dataset
    monitor=monitor.child(80))
  File "/home/alicja/Desktop/projects/cate/cate/ds/esa_cci_odp.py", line 1343, in make_local
    raise e
  File "/home/alicja/Desktop/projects/cate/cate/ds/esa_cci_odp.py", line 1336, in make_local
    self._update_local_ds(local_ds, time_range, region, var_names, monitor=monitor)
  File "/home/alicja/Desktop/projects/cate/cate/ds/esa_cci_odp.py", line 1126, in _update_local_ds
    self._update_ds_using_http(local_path, local_ds, selected_file_list, time_range, region, var_names, monitor)
  File "/home/alicja/Desktop/projects/cate/cate/ds/esa_cci_odp.py", line 1273, in _update_ds_using_http
    verb="synchronize", cause=e) from e
cate.core.ds.DataAccessError: Failed to synchronize data source "esacci.OZONE.mon.L3.NP.multi-sensor.multi-platform.MERGED.fv0002.r1": HTTP Error 308: Permanent Redirect
```

**Comment by forman** [comment]
@AliceBalfanz, is this still valid? If so, can you please try finding out, what causes this?

**Comment by AliceBalfanz** [comment]
This is not a cate-webui issue, opened cate issue, closing this one here.
