### ISSUE TITLE
File data source does not seem to have any datasets

### ISSUE THREAD

**Issue by AliceBalfanz** [CCI-Tools/cate-webui#73]
This issue seems to be OS related - tested on Ubuntu 20.04.1 LTS
When selecting a directory with netcdf files and adding it to the local sources, I receive an error message when opening the local source: 
`cate.core.ds.DataAccessError: Data source "local.cyano_version10" does not seem to have any datasets`

![image](https://user-images.githubusercontent.com/23457217/89982355-dcaf9400-dc75-11ea-96bd-0ee338f9c9a9.png)

```
Job: Opening data source "local.cyano_version10"
Message: Data source "local.cyano_version10" does not seem to have any datasets
Code: -32003
Method: set_workspace_resource
Exception: cate.core.ds.DataAccessError

Traceback (most recent call last):
  File "/home/alicja/Desktop/projects/cate/cate/util/web/jsonrpchandler.py", line 209, in send_service_method_result
    result = future.result()
  File "/home/alicja/miniconda3/envs/cate-env/lib/python3.7/concurrent/futures/_base.py", line 428, in result
    return self.__get_result()
  File "/home/alicja/miniconda3/envs/cate-env/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/home/alicja/miniconda3/envs/cate-env/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/alicja/Desktop/projects/cate/cate/util/web/jsonrpchandler.py", line 306, in call_service_method
    result = method(*method_params, monitor=monitor)
  File "/home/alicja/Desktop/projects/cate/cate/webapi/websocket.py", line 303, in set_workspace_resource
    monitor=monitor)
  File "/home/alicja/Desktop/projects/cate/cate/core/wsmanag.py", line 371, in set_workspace_resource
    workspace.execute_workflow(res_name=res_name, monitor=monitor)
  File "/home/alicja/Desktop/projects/cate/cate/core/workspace.py", line 667, in execute_workflow
    self.workflow.invoke_steps(steps, context=self._new_context(), monitor=monitor)
  File "/home/alicja/Desktop/projects/cate/cate/core/workflow.py", line 627, in invoke_steps
    steps[0].invoke(context=context, monitor=monitor)
  File "/home/alicja/Desktop/projects/cate/cate/core/workflow.py", line 318, in invoke
    self._invoke_impl(_new_context(context, step=self), monitor=monitor)
  File "/home/alicja/Desktop/projects/cate/cate/core/workflow.py", line 980, in _invoke_impl
    return_value = self._op(monitor=monitor, **input_values)
  File "/home/alicja/Desktop/projects/cate/cate/core/op.py", line 216, in __call__
    return_value = self._wrapped_op(**input_values)
  File "/home/alicja/Desktop/projects/cate/cate/ops/io.py", line 84, in open_dataset
    monitor=monitor)
  File "/home/alicja/Desktop/projects/cate/cate/core/ds.py", line 678, in open_dataset
    return data_source.open_dataset(time_range, region, var_names, monitor=monitor)
  File "/home/alicja/Desktop/projects/cate/cate/ds/local.py", line 173, in open_dataset
    raise self._empty_error(time_range)
cate.core.ds.DataAccessError: Data source "local.cyano_version10" does not seem to have any datasets
```

**Comment by forman** [comment]
Blocker, because users cannot have their own data sources

**Comment by forman** [comment]
@AliceBalfanz , can you please retry with a Cate server without the `--root` option set.

**Comment by AliceBalfanz** [comment]
Closing, because it was a problem of the netcdf files and not a Cate issue.
